FROM mcr.microsoft.com/dotnet/sdk:5.0
# copy everything else and build app

COPY . ./
RUN dotnet restore
RUN dotnet publish -c release -o /app --no-restore
ENV ASPNETCORE_URLS=http://+:80

WORKDIR /app
EXPOSE 80
ENTRYPOINT ["dotnet", "WebAppDocker.dll"]